### ISSUE TITLE
Python Mailing List

### ISSUE THREAD

**Issue by baryonyx5** [cdwlabs/python-book-club#1]
This issue is used as a generic mailing list for Python Book Club team members.

Include @cdwlabs/python-book-club  somewhere in your message to CC all team members.

**Comment by cclouse** [comment]
Cisco APO Python Study Group 
We are ready to kick off another study group to coincide with the spring session of Coursera’s “An Introduction to Interactive Programming in Python” course.  A few changes from last session, if you want to be included on future mailings please visit our new opt-in mailer to sign up. A call has been setup and the WebEx info is available out on the APO Python Study Group Community. We will continue to use this site to post the latest information from the class, recordings of past calls, and additional resources to help you put those python skills to work.
Even if you do not intend on taking the course again, there is plenty of new content planned for this session to help you begin to apply the python skills you learned to APIs, Nexus 7K/9K, ACI, and more.  

https://communities.cisco.com/groups/apo-python-study-group 
Signup here: http://cisco.cvent.com/Python

cc/ @cdwlabs/python-book-club

**Comment by baryonyx5** [comment]
@cdwlabs/python-book-club 

In case you did not receive the Outlook cancellation, the book club meeting for today (5/14) is cancelled.

**Comment by baryonyx5** [comment]
Follow up from 5/28 meeting...

**No. 1**
Brad asked about structuring python code. This brought to mind a related youtube lecture I found interesting.  
https://www.youtube.com/watch?v=x-kB2o8sd5c
This speaker has many lectures on youtube and he's very good.

Also, somewhat related, the Python style guide provides best practice coding conventions. 
https://www.python.org/dev/peps/pep-0008/

Google has their own python style guide. I make a point to stick to the google document string conventions for documenting code inline
http://google-styleguide.googlecode.com/svn/trunk/pyguide.html#Comments

**No. 2**
For anyone interested, here's a link where you can purchase online programming courses pretty cheaply.  I haven't taken any of these so I can't speak to the quality. 

https://store.boingboing.net/sales/learn-to-code-2015-course-bundle  
https://store.boingboing.net/sales/python-programming-for-beginners




@cdwlabs/python-book-club

**Comment by cclouse** [comment]
Is anyone else having issues in Safari Books getting to the videos within the reading?
@cdwlabs/python-book-club

**Comment by pinterb** [comment]
/cc @cdwlabs/python-book-club 

Beyond PEP 8, Best Practices for Intelligible code:
https://www.youtube.com/watch?v=wf-BqAjZb8M
